
image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: 'Push code to GitHub Package Registry'
          script: 
            # Set Git user identity
            - git config --global user.email ${GITHUB_EMAIL}
            - git config --global user.email ${GITHUB_USERNAME}

            - echo "Configured Git User Email: $(git config --global user.email)"
            - echo "Configured Git User Name: $(git config --global user.name)"
