image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: 'Push code to GitHub Package Registry'
          script: 
            # Set Git user identity
            - git config --global user.email ssuriya3098@gmail.com
            - git config --global user.name Suriyasiva


            - git remote remove origin
            - git remote add origin https://Suriyasiva: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@github.com/Suriyasiva/octobell-web-components.git
            - git pull origin master --allow-unrelated-histories --no-rebase
            - git push origin master
