image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: 'Push code to GitHub Package Registry'
          script: 
            # Set Git user identity
            - git config --global user.email "${GITHUB_EMAIL}"
            - git config --global user.name "${GITHUB_USERNAME}"

            - git remote add github https://Suriyasiva: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@github.com/Suriyasiva/octobell-web-components.git
            - git pull github master --no-rebase
            - git push github master
